# Generated by Django 3.0.1 on 2020-01-05 14:25

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='son',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='son',
            field=models.ManyToManyField(blank=True, null=True, related_name='son', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='suspention_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 5, 14, 25, 26, 745532)),
        ),
    ]
