# Generated by Django 3.0.1 on 2020-01-17 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='number_of_moves',
            field=models.IntegerField(default=0),
        ),
    ]
