# Generated by Django 3.0.1 on 2020-01-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='suspention_time',
            field=models.DateTimeField(default=0),
        ),
    ]
