# Generated by Django 3.0.1 on 2020-01-15 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_userprofile_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='suspention_time',
            new_name='suspension_time',
        ),
    ]
