# Generated by Django 3.0.1 on 2020-01-18 19:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0002_auto_20200118_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='limit',
            field=models.IntegerField(default=99999),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='time_start',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 18, 19, 20, 37, 572740, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='son',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dad', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='suspention_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 18, 19, 20, 37, 568740, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='winning',
            name='win_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 18, 19, 20, 37, 571740, tzinfo=utc)),
        ),
    ]
