# Generated by Django 3.0.1 on 2019-12-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20191229_0213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win_date', models.DateTimeField(verbose_name='date won')),
            ],
        ),
    ]
