# Generated by Django 3.0.1 on 2020-01-05 14:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0002_auto_20200105_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='son',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='son',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='son', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='suspention_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 5, 14, 40, 19, 977730)),
        ),
    ]
