# Generated by Django 3.0.1 on 2020-01-05 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20200105_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='suspention_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 5, 19, 29, 50, 158338)),
        ),
    ]
