# Generated by Django 3.0.1 on 2019-12-29 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20191229_0213'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
