# Generated by Django 3.0.1 on 2020-01-17 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_gamesession_number_of_moves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='time_start',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 17, 21, 34, 1, 39547)),
        ),
    ]
