# Generated by Django 3.0.1 on 2020-01-05 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20200105_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='suspention_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 5, 14, 57, 52, 343941)),
        ),
    ]
