# Generated by Django 3.0.1 on 2020-01-15 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20200115_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='suspension_time',
            new_name='suspention_time',
        ),
    ]
