# Generated by Django 3.0.1 on 2020-01-17 21:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20200117_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prize',
            name='condition',
        ),
        migrations.AddField(
            model_name='prize',
            name='condition_type',
            field=models.CharField(choices=[('time', 'time'), ('moves', 'moves'), ('mistakes', 'mistakes')], default='time', max_length=20),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='time_start',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 17, 21, 40, 9, 116600)),
        ),
        migrations.AlterField(
            model_name='prize',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
