# Generated by Django 3.0.1 on 2019-12-29 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_winning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winning',
            name='win_date',
        ),
    ]
