# Generated by Django 3.0.1 on 2020-01-18 19:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20200118_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='time_start',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 18, 19, 23, 28, 512517, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='limit',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 18, 19, 23, 28, 508517, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='suspention_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 18, 19, 23, 28, 508517, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='winning',
            name='win_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 18, 19, 23, 28, 511517, tzinfo=utc)),
        ),
    ]
