# Generated by Django 3.0.1 on 2020-01-17 21:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20200117_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='condition',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='time_start',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 17, 21, 55, 16, 220484)),
        ),
    ]
