# Generated by Django 3.0.1 on 2020-01-19 02:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20200118_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='time_start',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 19, 2, 2, 45, 764117, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='limit',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 19, 2, 2, 45, 757117, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='suspention_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 19, 2, 2, 45, 757117, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='winning',
            name='win_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 19, 2, 2, 45, 762117, tzinfo=utc)),
        ),
    ]
