# Generated by Django 3.0.1 on 2019-12-29 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_remove_winning_win_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='winning',
            name='win_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 29, 12, 47, 33, 485188), verbose_name='date won'),
            preserve_default=False,
        ),
    ]
