# Generated by Django 3.0.1 on 2020-01-15 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20200115_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='winning',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='suspention_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 15, 13, 52, 3, 837152)),
        ),
    ]
