# Generated by Django 3.0.2 on 2020-01-17 00:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20200115_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='winning',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='suspention_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 17, 2, 35, 14, 17795)),
        ),
    ]
