# Generated by Django 3.0.1 on 2020-01-17 22:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20200117_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='time_start',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 17, 22, 7, 2, 744895)),
        ),
        migrations.AlterField(
            model_name='winning',
            name='win_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 17, 22, 7, 2, 742894)),
        ),
    ]
