# Generated by Django 3.0.1 on 2019-12-29 14:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_winning_win_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winning',
            name='id',
        ),
        migrations.AddField(
            model_name='winning',
            name='win_user',
            field=models.ForeignKey(default=datetime.datetime(2019, 12, 29, 14, 1, 56, 481045), on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='registration.User'),
            preserve_default=False,
        ),
    ]
