# Generated by Django 3.0.1 on 2020-01-19 02:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20200119_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='time_start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='limit',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='suspention_time',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='winning',
            name='win_date',
            field=models.DateTimeField(),
        ),
    ]
