# Generated by Django 3.0.1 on 2020-01-15 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20200115_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='limit',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='suspention_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 15, 17, 4, 39, 356454)),
        ),
    ]
