# Generated by Django 3.0.1 on 2020-01-17 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20200117_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='time_start',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 17, 22, 18, 34, 134440)),
        ),
        migrations.AlterField(
            model_name='winning',
            name='win_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 17, 22, 18, 34, 133440)),
        ),
    ]
