# Generated by Django 3.0.1 on 2019-12-29 14:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20191229_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='winning',
            name='id',
            field=models.AutoField(auto_created=True, default=datetime.datetime(2019, 12, 29, 14, 12, 14, 720194), primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='winning',
            name='win_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.User'),
        ),
    ]
