# Generated by Django 3.0.2 on 2020-01-19 07:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0006_auto_20200117_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='number_of_moves',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prize',
            name='condition_type',
            field=models.CharField(choices=[('time', 'time'), ('moves', 'moves'), ('mistakes', 'mistakes')], default='time', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='limit',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='time_start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='prize',
            name='condition',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='prize',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='son',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dad', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='suspention_time',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='winning',
            name='win_date',
            field=models.DateTimeField(),
        ),
    ]
