# Generated by Django 3.0.1 on 2019-12-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20191229_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='winning',
            name='winning_id',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
