# Generated by Django 3.0.1 on 2020-01-18 18:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20200118_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='time_start',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 18, 18, 28, 3, 47311, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='suspention_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 18, 18, 28, 3, 41311, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='winning',
            name='win_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 18, 18, 28, 3, 46311, tzinfo=utc)),
        ),
    ]
