# Generated by Django 3.0.1 on 2019-12-29 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_winning_winning_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winning',
            name='win_user',
        ),
        migrations.RemoveField(
            model_name='winning',
            name='winning_id',
        ),
    ]
