# Generated by Django 3.0.1 on 2019-12-29 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_auto_20191229_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='winning',
            name='win_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.User'),
        ),
        migrations.AlterField(
            model_name='winning',
            name='win_date',
            field=models.DateTimeField(),
        ),
    ]
