# Generated by Django 3.0.1 on 2019-12-29 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_auto_20191229_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('condition', models.CharField(max_length=200)),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='winning',
            name='win_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='winning',
            name='win_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.User'),
        ),
        migrations.AddField(
            model_name='winning',
            name='prize',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.Prize'),
        ),
    ]
