# Generated by Django 3.0.1 on 2019-12-29 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_auto_20191229_1444'),
        ('registration', '0004_prize_winning'),
    ]

    operations = [
    ]
