# Generated by Django 3.0.1 on 2019-12-29 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_merge_20191229_1457'),
        ('registration', '0003_auto_20191229_1455'),
    ]

    operations = [
    ]
